# Generated by Django 5.0.7 on 2024-07-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_basic_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chaivariety",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="chaivariety",
            name="image",
            field=models.ImageField(upload_to="Tea_images/"),
        ),
    ]
