# Generated by Django 5.0.7 on 2024-07-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_basic_app", "0002_chaivariety_description_alter_chaivariety_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="chaivariety",
            name="pricing",
            field=models.DecimalField(decimal_places=2, default=350, max_digits=5),
        ),
    ]
