[tool.poetry]
name = "django-project"
version = "0.1.0"
description = ""
authors = ["ahmedcurious <ahmed_naseem1@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.0.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
